# Generated by Django 4.2.4 on 2023-08-02 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.IntegerField(choices=[('1', 'Administrador'), ('2', 'Gerente'), ('3', 'Funcionário')], verbose_name='Cargo'),
        ),
    ]
